# # DDU RX
# create_hw_probe -map probe0[15:0]     rxdata_ddu_ch_1[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[31:16]    rxdata_ddu_ch_3[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[35:32]    rxd_valid_ddu[3:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[36]       rxready_ddu [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[52:37]    prbs_anyerr_ddu_1[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[68:53]    prbs_anyerr_ddu_3[15:0] [get_hw_ilas hw_ila_1]

# # DDU TX
# create_hw_probe -map probe0[15:0]     txdata_ddu_prbs_int[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[31:16]    txdata_ddu_cntr_int[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[32]       txd_valid_ddu_int [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[48:33]    txd_ddu_init_ctr[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[64:49]    txdata_spy_int[15:0] [get_hw_ilas hw_ila_3]

# SPY RX
create_hw_probe -map {probe0[15:0]}   rxdata_spy[15:0]       [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[17:16]}  spy_codevalid[1:0]     [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[25:24]}  spy_rxcharisk[1:0]     [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[29:28]}  spy_rxdisperr[1:0]     [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[33:32]}  spy_rxchariscomma[1:0] [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[37:36]}  spy_rxnotintable[1:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[20]}     spy_bad_rx             [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[21]}     spy_rxd_valid          [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[22]}     spy_rxbyteisaligned    [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[23]}     spy_rxbyterealign      [get_hw_ilas hw_ila_2]

# SPY TX
create_hw_probe -map {probe0[15:0]}   userdata_tx_int[15:0]  [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[31:16]}  txdata_spy[15:0]       [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[32]}     txd_valid_spy          [get_hw_ilas hw_ila_3]

# # MGT_SPY
# create_hw_probe -map {probe0[15:0]}   gtwiz_userdata_rx_spy[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[19:16]}  ch0_codevalid[3:0]          [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[20]}     bad_rx_spy                  [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[21]}     rxd_valid_int               [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[27:24]}  ch0_rxcharisk[3:0]          [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[31:28]}  ch0_rxdisperr[3:0]          [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[35:32]}  ch0_rxchariscomma[3:0]      [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[39:36]}  ch0_rxnotintable[3:0]       [get_hw_ilas hw_ila_3]

# # MGT_DDU
# create_hw_probe -map {probe0[63:0]}  gtwiz_userdata_rx_int[63:0] [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[15:0]}  rxdata_ddu_ch1[15:0]        [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[31:16]} rxdata_ddu_ch2[15:0]        [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[47:32]} rxdata_ddu_ch3[15:0]        [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[63:48]} rxdata_ddu_ch4[15:0]        [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[65:64]} codevalid_ch1[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[69:68]} codevalid_ch3[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[73:70]} rxbyteisaligned_int[3:0]    [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[77:74]} rxbyterealign_int[3:0]      [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[79:78]} rxnotintable_ch1[1:0]       [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[81:80]} rxnotintable_ch3[1:0]       [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[83:82]} rxdisperr_ch1[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[85:84]} rxdisperr_ch3[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[87:86]} rxcharisk_ch1[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[89:88]} rxcharisk_ch3[1:0]          [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[91:90]} rxchariscomma_ch1[1:0]      [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[93:92]} rxchariscomma_ch3[1:0]      [get_hw_ilas hw_ila_2]
# create_hw_probe -map {probe0[97:94]} bad_rx_int[3:0]             [get_hw_ilas hw_ila_2]

# MGT_CFEB

# create_hw_probe -map {probe0[31:16]}    rxdata_i_feb1[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[33:32]}    codevalid_feb1[1:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[41:40]}    rxcharisk_feb1[1:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[43:42]}    rxdisperr_feb1[1:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[45:44]}    rxchariscomma_feb1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[47:46]}    rxnotintable_feb1[1:0]  [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[34]}       rxd_valid_feb1          [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[35]}       crc_valid_feb1          [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[36]}       good_crc_feb1           [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[37]}       bad_rx_feb1             [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[38]}       rxbyteisaligned_feb1    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[39]}       rxbyterealign_feb1      [get_hw_ilas hw_ila_1]

# create_hw_probe -map {probe0[255:240]}  rxdata_o_feb6[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[271:256]}  rxdata_i_feb6[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[273:272]}  codevalid_feb6[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[281:280]}  rxcharisk_feb6[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[283:282]}  rxdisperr_feb6[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[285:284]}  rxchariscomma_feb6[1:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[287:286]}  rxnotintable_feb6[1:0]  [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[274]}      rxd_valid_feb6          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[275]}      crc_valid_feb6          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[276]}      good_crc_feb6           [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[277]}      bad_rx_feb6             [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[278]}      rxbyteisaligned_feb6    [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[279]}      rxbyterealign_feb6      [get_hw_ilas hw_ila_1]

# create_hw_probe -map {probe0[303:288]}  rxdata_o_feb7[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[319:304]}  rxdata_i_feb7[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[321:320]}  codevalid_feb7[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[329:328]}  rxcharisk_feb7[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[331:330]}  rxdisperr_feb7[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[333:332]}  rxchariscomma_feb7[1:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[335:334]}  rxnotintable_feb7[1:0]  [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[322]}      rxd_valid_feb7          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[323]}      crc_valid_feb7          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[324]}      good_crc_feb7           [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[325]}      bad_rx_feb7             [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[326]}      rxbyteisaligned_feb7    [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[327]}      rxbyterealign_feb7      [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[15:0]}     rxdata_o_feb1[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[63:48]}    rxdata_o_feb2[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[111:96]}   rxdata_o_feb3[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[159:144]}  rxdata_o_feb4[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[207:192]}  rxdata_o_feb5[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[255:240]}  rxdata_o_feb6[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[303:288]}  rxdata_o_feb7[15:0]     [get_hw_ilas hw_ila_1]

create_hw_probe -map {probe0[31:16]}    rxdata_i_feb1[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[79:64]}    rxdata_i_feb2[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[127:112]}  rxdata_i_feb3[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[175:160]}  rxdata_i_feb4[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[223:208]}  rxdata_i_feb5[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[271:256]}  rxdata_i_feb6[15:0]     [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[319:304]}  rxdata_i_feb7[15:0]     [get_hw_ilas hw_ila_1]

create_hw_probe -map {probe0[38]}       rxbyteisaligned_feb1    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[86]}       rxbyteisaligned_feb2    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[134]}      rxbyteisaligned_feb3    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[182]}      rxbyteisaligned_feb4    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[230]}      rxbyteisaligned_feb5    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[278]}      rxbyteisaligned_feb6    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[326]}      rxbyteisaligned_feb7    [get_hw_ilas hw_ila_1]

# create_hw_probe -map {probe0[352:346]}  kill_rxout[6:0]        [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[359:353]}  kill_rxpd[6:0]         [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[360]}      reset                   [get_hw_ilas hw_ila_1]

# create_hw_probe -map {probe0[63:48]}   rxdata_o_cch3[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[79:64]}   rxdata_i_cch3[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[81:80]}   codevalid_cch3[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[89:88]}   rxcharisk_cch3[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[91:90]}   rxdisperr_cch3[1:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[93:92]}   rxchariscomma_cch3[1:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[95:94]}   rxnotintable_cch3[1:0]  [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[102:96]}  kill_rxout[6:0]        [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[109:103]} kill_rxpd[6:0]         [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[82]}      rxd_valid_cch3          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[83]}      crc_valid_cch3          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[84]}      good_crc_cch3           [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[85]}      bad_rx_cch3             [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[86]}      rxbyteisaligned_int_3  [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[87]}      rxbyterealign_int_3    [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[110]}     reset                  [get_hw_ilas hw_ila_1]

# # SYSTEM_TEST
# create_hw_probe -map {probe0[48:0]}     otmb_tx[48:0]             [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[64:49]}    otmb_prbs_tx_en_cnt[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[80:65]}    otmb_tx_good_cnt[15:0]    [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[96:81]}    otmb_tx_err_cnt[15:0]     [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[97]}       w_otmb_prbs_en            [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[98]}       r_otmb_prbs_en_cnt        [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[99]}       r_otmb_prbs_good_cnt      [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[100]}      r_otmb_prbs_err_cnt       [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[101]}      w_otmb_prbs_cnt_rst       [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[102]}      otmb_prbs_tx_en           [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[103]}      otmb_prbs_tx_rst          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[104]}      q_otmb_prbs_tx_en         [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[105]}      qq_otmb_prbs_tx_en        [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[106]}      otmb_prbs_tx              [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[107]}      otmb_prbs_tx_err          [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[156:108]}  mux_otmb_tx[48:0]         [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[172:157]}  outdata_inner[15:0]       [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[173]}      dtack_inner               [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[174]}      start_otmb_prbs_rx        [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[175]}      otmb_prbs_rx_en           [get_hw_ilas hw_ila_1]
# create_hw_probe -map {probe0[176]}      otmb_prbs_rx              [get_hw_ilas hw_ila_1]


# trgcntrl
create_hw_probe -map {probe0[0]}          raw_l1a                   [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[1]}          raw_lct_0                 [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[2]}          alct_dav                  [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[3]}          otmb_dav                  [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[8]}          l1a                       [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[9]}          fifo_push_inner           [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[10]}         alct_dav_sync             [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[11]}         otmb_dav_sync             [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[18:12]}      raw_lct[7:1]              [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[25:19]}      lct[7:1]                  [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[32:26]}      l1a_match[7:1]            [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[41:33]}      fifo_l1a_match[9:1]       [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[50:42]}      kill[9:1]                 [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[55:51]}      lct_q1[4:0]               [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[60:56]}      lct_q2[4:0]               [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[66:61]}      lct_l1a_dly[5:0]          [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[72:67]}      otmb_push_dly[5:0]        [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[78:73]}      alct_push_dly[5:0]        [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[84:79]}      push_dly[5:0]             [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[86]}         cal_mode                  [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[87]}         cal_l1a                   [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[88]}         cal_lct                   [get_hw_ilas hw_ila_4]

