
# # DDU RX
# create_hw_probe -map probe0[15:0]     rxdata_ddu_ch_1[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[31:16]    rxdata_ddu_ch_3[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[35:32]    rxd_valid_ddu[3:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[36]       rxready_ddu [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[52:37]    prbs_anyerr_ddu_1[15:0] [get_hw_ilas hw_ila_1]
# create_hw_probe -map probe0[68:53]    prbs_anyerr_ddu_3[15:0] [get_hw_ilas hw_ila_1]

# # DDU TX
# create_hw_probe -map probe0[15:0]     txdata_ddu_prbs_int[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[31:16]    txdata_ddu_cntr_int[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[32]       txd_valid_ddu_int [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[48:33]    txd_ddu_init_ctr[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map probe0[64:49]    txdata_spy_int[15:0] [get_hw_ilas hw_ila_3]

# # SPY RX
# create_hw_probe -map {probe0[15:0]}   rxdata_spy[15:0] [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[16]}     rxd_valid_spy [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[17]}     rxready_spy [get_hw_ilas hw_ila_3]
# create_hw_probe -map {probe0[34:19]}  prbs_anyerr_spy[15:0] [get_hw_ilas hw_ila_3]

# # SPY TX
# create_hw_probe -map {probe0[15:0]}   txdata_spy[15:0] [get_hw_ilas hw_ila_5]
# create_hw_probe -map {probe0[16]}     txd_valid_spy [get_hw_ilas hw_ila_5]

# MGT_SPY
create_hw_probe -map {probe0[15:0]}   gtwiz_userdata_rx_spy[15:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[19:16]}  ch0_codevalid[3:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[20]}     bad_rx_spy  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[21]}     rxd_valid_int  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[27:24]}  ch0_rxcharisk[3:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[31:28]}  ch0_rxdisperr[3:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[35:32]}  ch0_rxchariscomma[3:0]  [get_hw_ilas hw_ila_2]
create_hw_probe -map {probe0[39:36]}  ch0_rxnotintable[3:0]  [get_hw_ilas hw_ila_2]

# MGT_DDU
create_hw_probe -map {probe0[63:0]}  gtwiz_userdata_rx_int[63:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[15:0]}  rxdata_ddu_ch1[15:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[31:16]} rxdata_ddu_ch2[15:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[47:32]} rxdata_ddu_ch3[15:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[63:48]} rxdata_ddu_ch4[15:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[65:64]} codevalid_ch1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[69:68]} codevalid_ch3[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[73:70]} rxbyteisaligned_int[3:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[77:74]} rxbyterealign_int[3:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[79:78]} rxnotintable_ch1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[81:80]} rxnotintable_ch3[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[83:82]} rxdisperr_ch1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[85:84]} rxdisperr_ch3[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[87:86]} rxcharisk_ch1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[89:88]} rxcharisk_ch3[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[91:90]} rxchariscomma_ch1[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[93:92]} rxchariscomma_ch3[1:0] [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[97:94]} bad_rx_int[3:0] [get_hw_ilas hw_ila_1]

# MGT_CFEB
create_hw_probe -map {probe0[15:0]}    rxdata_o_ch1[15:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[31:16]}   rxdata_i_ch1[15:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[33:32]}   codevalid_ch1[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[41:40]}   rxcharisk_ch1[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[43:42]}   rxdisperr_ch1[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[45:44]}   rxchariscomma_ch1[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[47:46]}   rxnotintable_ch1[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[34]}      rxd_valid_ch1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[35]}      crc_valid_ch1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[36]}      good_crc_ch1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[37]}      bad_rx_ch1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[38]}      rxbyteisaligned_int_1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[39]}      rxbyterealign_int_1 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[63:48]}   rxdata_o_ch3[15:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[79:64]}   rxdata_i_ch3[15:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[81:80]}   codevalid_ch3[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[89:88]}   rxcharisk_ch3[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[91:90]}   rxdisperr_ch3[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[93:92]}   rxchariscomma_ch3[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[95:94]}   rxnotintable_ch3[1:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[102:96]}  kill_rxout[6:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[109:103]} kill_rxpd[6:0] [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[82]}      rxd_valid_ch3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[83]}      crc_valid_ch3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[84]}      good_crc_ch3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[85]}      bad_rx_ch3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[86]}      rxbyteisaligned_int_3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[87]}      rxbyterealign_int_3 [get_hw_ilas hw_ila_3]
create_hw_probe -map {probe0[110]}     reset [get_hw_ilas hw_ila_3]

# SYSTEM_TEST
create_hw_probe -map {probe0[48:0]}     otmb_tx[48:0]             [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[64:49]}    otmb_prbs_tx_en_cnt[15:0] [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[80:65]}    otmb_tx_good_cnt[15:0]    [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[96:81]}    otmb_tx_err_cnt[15:0]     [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[97]}       w_otmb_prbs_en            [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[98]}       r_otmb_prbs_en_cnt        [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[99]}       r_otmb_prbs_good_cnt      [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[100]}      r_otmb_prbs_err_cnt       [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[101]}      w_otmb_prbs_cnt_rst       [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[102]}      otmb_prbs_tx_en           [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[103]}      otmb_prbs_tx_rst          [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[104]}      q_otmb_prbs_tx_en         [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[105]}      qq_otmb_prbs_tx_en        [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[106]}      otmb_prbs_tx              [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[107]}      otmb_prbs_tx_err          [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[156:108]}  mux_otmb_tx[48:0]         [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[172:157]}  outdata_inner[15:0]       [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[173]}      dtack_inner               [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[174]}      start_otmb_prbs_rx        [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[175]}      otmb_prbs_rx_en           [get_hw_ilas hw_ila_4]
create_hw_probe -map {probe0[176]}      otmb_prbs_rx              [get_hw_ilas hw_ila_4]

